### ISSUE TITLE
Modelo de banco de dados

### ISSUE THREAD

**Issue by lilialnas** [desireefernandes/TutorEasy#1]
Implementação do modelo de banco de dados

- [x] Implementar modelo ER
- [x] Implementar modelo lógico
- [x] Gerar Script de modelo físico
