### ISSUE TITLE
Front-end tela inicial

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#5]
Eu como **desenvolvedor** quero **planejar e elaborar a tela inicial** organizando a identidade visual, design de interface e fluxo do sistema para **criar uma tela na qual o usuário terá acesso ao sistema.**

- [x] Definir fluxo de interação do sistema
- [x] Criação do esquema do fluxo
- [ ] Criação do protótipo #7 
- [x] Criação da página inicial #8 
- [x] Análise e procura de banco de imagens

**Comment by anabeatriiz** [comment]
Links que selecionei para o banco de imagens

https://undraw.co/illustrations
https://blush.design/collections
https://www.humaaans.com/
