### ISSUE TITLE
Front-end tela inicial

### ISSUE THREAD

**Issue by desireefernandes** [desireefernandes/TutorEasy#8]
- [ ]  Definição do fluxo das telas do sistema
- [ ]  Criação do esquema do fluxo
- [ ]  Criação do protótipo
- [ ]  Criação da página inicial
